OrdererOrgs:
    - Name: Orderer
      Domain: pjud.cl
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: PoderJudicial
      Domain: poderjudicial.pjud.cl
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: ParticipanteCausa
      Domain: participantecausa.pjud.cl
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: EntidadExterna
      Domain: entidadexterna.pjud.cl
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
